title: Techie Joe's Website
description: A site hosted on GitHub showcasing my work and interests.

remote_theme: techie-joe/mallet
remote_theme_build_revision: 5a931b348341d49384d42974e8cef2fcb33bafca
